apiVersion: apps/v1
kind: Deployment
metadata:
  name: presentacion-deployment
  labels:
    app: presentacion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presentacion
  template:
    metadata:
      labels:
        app: presentacion
    spec:
      containers:
        - name: presentacion
          image: presentacion:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: presentacion-service
spec:
  type: NodePort
  selector:
    app: presentacion
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
